version: '3.7'

services:
  jiralert:
    image: gen921/jiralert:latest
    hostname: jiralert

    ports:
      - 9097:9097

    environment:
      - TZ=Europe/Kiev
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - LANGUAGE=en_US:en

    volumes:
      - ./volumes/config:/etc/jiralert/config

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
