---
# Global defaults, applied to all receivers where not explicitly overridden. Optional.
defaults:
  # API access fields.
  api_url: <your_jira_url>
  user: <your_fira_user>
  password: '<jira_user_password>'
  # Alternatively to user and password use a Personal Access Token
  # personal_access_token: "Your Personal Access Token". See https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html

  # The type of JIRA issue to create. Required.
  issue_type: Bug
  # Issue priority. Optional.
  priority: '{{ template "jira.priority" . }}'
  # Go template invocation for generating the summary. Required.
  summary: '{{ template "jira.summary" . }}'
  # Go template invocation for generating the description. Optional.
  description: '{{ template "jira.description" . }}'
  # State to transition into when reopening a closed issue. Required.
  reopen_state: "Backlog"
  # Do not reopen issues with this resolution. Optional.
  wont_fix_resolution: "Won't Fix"
  # Amount of time after being closed that an issue should be reopened, after which, a new issue is created.
  # Optional (default: always reopen)
  reopen_duration: 0h
  # Static label that will be added to the JIRA ticket alongisde the JIRALERT{...} or ALERT{...} label
  # Other projects are the projects to search for existing issues for the given alerts if
  # the main project does not have it. If no issue was found in, the main projects will
  # be used to create a new one. If the old issue is found in one of the other projects
  # (first found is used in case of duplicates) that old project's issue will be used for
  # alert updates instead of creating on in the main project.

# Receiver definitions. At least one must be defined.
receivers:
    # Must match the Alertmanager receiver name. Required.
  - name: 'jira-test'
    # JIRA project to create the issue in. Required.
    project: <jira_project_name>
    # Copy all Prometheus labels into separate JIRA labels. Optional (default: false).
#    add_group_labels: false
    # Include ticket update as comment too. Optional (default: false).
#    update_in_comment: false
    # Will be merged with the static_labels from the default map
    priority: 'Medium'


  - name: 'jira-test2'
    project: <jira_project_name>
    # Overrides default.
    issue_type: Task
    # JIRA components. Optional.
#    components: ['Operations']
    # Standard or custom field values to set on created issue. Optional.
    priority: 'Medium'
    #
    # See https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#setting-custom-field-data-for-other-field-types for further examples.
#    fields:
      # TextField
#      customfield_10001: "Random text"
      # SelectList
#      customfield_10002: {"value": "red"}
      # MultiSelect
#      customfield_10003: [{"value": "red"}, {"value": "blue"}, {"value": "green"}]
    #
    # Automatically resolve jira issues when alert is resolved. Optional. If declared, ensure state is not an empty string.
    auto_resolve:
      state: 'Done'
    # Include ticket update as comment too. Optional (default: false).
#    update_in_comment: true


# File containing template definitions. Required.
template: jiralert.tmpl
